### ISSUE TITLE
Conv2D COSIM kernel building failed

### ISSUE THREAD

**Issue by yodada** [cornell-brg/hb-pytorch#14]
## 🐛 Bug

Kernel building failed when running on COSIM. Undefined references to `bsg_printf` and `std::ios_base::Init::~Init()`

## To Reproduce

1. Build PyTorch for COSIM
1. Goto `hammerblade/torch`
1. `make kernel.riscv`

## Possible Reasons

1. `<iostream>` is included in `kernel_conv.cpp`
1. `bsg_printf` is not included correctly in `Makefile`

**Comment by yodada** [comment]
Yeah we need this line in the kernel `Makefile`
`KERNEL_CLIBRARIES   += $(BSG_MANYCORE_DIR)/software/bsg_manycore_lib/bsg_printf.c` and remove that `#include <iostream>`

I'll manually run COSIM tests before future merges.

**Comment by vb000** [comment]
Sorry about that. Yes, missed running it on cosim. On it.
