### ISSUE TITLE
Addmm failing for some dimensions

### ISSUE THREAD

**Issue by vb000** [cornell-brg/hb-pytorch#35]
## 🐛 Bug

Apparently, `addmm_hb` kernel is failing for dimensions greater than 10, possibly due to index mis-calculation with `BLOACK_SIZE = 10`.

## To Reproduce

1. Run the following testcase:

```
    def test_torch_addmm_6():
        M = torch.rand(1, 11)
        M_h = M.hammerblade()
        mat1 = torch.rand(1, 1)
        mat1_h = mat1.hammerblade()
        mat2 = torch.rand(1, 11)
        mat2_h = mat2.hammerblade()
        out = torch.addmm(M, mat1, mat2)
        out_h = torch.addmm(M_h, mat1_h, mat2_h)
        assert out_h.device == torch.device("hammerblade")
        assert torch.allclose(out_h.cpu(), out)
```

2. You'd observe following error. Note that only 11th element is mis-computed.
```
>       assert torch.allclose(out_h.cpu(), out)
E       AssertionError: assert False
E        +  where False = <built-in method allclose of type object at 0x7fbbb836e180>(tensor([[0.8388, 0.9638, 0.9824, 0.9500, 0.9602, 0.7416, 0.2890, 0.8992, 0.1118,\n         1.1431, 0.9941]]), tensor([[0.8388, 0.9638, 0.9824, 0.9500, 0.9602, 0.7416, 0.2890, 0.8992, 0.1118,\n         1.1431, 1.1324]]))
E        +    where <built-in method allclose of type object at 0x7fbbb836e180> = torch.allclose
E        +    and   tensor([[0.8388, 0.9638, 0.9824, 0.9500, 0.9602, 0.7416, 0.2890, 0.8992, 0.1118,\n         1.1431, 0.9941]]) = <built-in method cpu of Tensor object at 0x7fbbaf037318>()
E        +      where <built-in method cpu of Tensor object at 0x7fbbaf037318> = tensor([[0.8388, 0.9638, 0.9824, 0.9500, 0.9602, 0.7416, 0.2890, 0.8992, 0.1118,\n         1.1431, 0.9941]], device='hammerblade').cpu
```

**Comment by yodada** [comment]
Seems only the very last element is wrong. but another question is ... if it fails for (1, 11) and (11, 1), why this one passes
https://github.com/cornell-brg/hb-pytorch/blob/3a7ef13c92597d72d507be01ab2ebaf0737f2bb2/hammerblade/torch/tests/test_addmm.py#L50-L60

**Comment by vb000** [comment]
No just one, but all greater then 10 for these dimensions.

**Comment by yodada** [comment]
Looks like there is a buffer being used without proper initialization?
https://github.com/cornell-brg/hb-pytorch/pull/44#issuecomment-609044202

**Comment by yodada** [comment]
I just tested #44 with explicit initialization, but unfortunately it does not fix the problem. :(

**Comment by yodada** [comment]
Oooops. I take it back. I copied one line wrong. #44 *does* fix this test
```python
def test_torch_addmm_6():
    M = torch.zeros(1, 11)
    M_h = M.hammerblade()
    mat1 = torch.ones(1, 1)
    mat1_h = mat1.hammerblade()
    mat2 = torch.ones(1, 11)
    mat2_h = mat2.hammerblade()
    out = torch.addmm(M, mat1, mat2)
    out_h = torch.addmm(M_h, mat1_h, mat2_h)
    assert out_h.device == torch.device("hammerblade")
    assert torch.allclose(out_h.cpu(), out)
```

**Comment by kzheng9** [comment]
I just tried this test and it is still failing.. I am looking into it now.


`def test_torch_addmm_4():`

    M = torch.randn(1, 11)
    M_h = M.hammerblade()
    mat1 = torch.randn(1, 1)
    mat1_h = mat1.hammerblade()
    mat2 = torch.randn(1, 11)
    mat2_h = mat2.hammerblade()
    out = torch.addmm(M, mat1, mat2)
    out_h = torch.addmm(M_h, mat1_h, mat2_h)
    assert out_h.device == torch.device("hammerblade")
    assert torch.allclose(out_h.cpu(), out, 1e-07, 1e-04)

**Comment by kzheng9** [comment]
Please see #50 for a fix to this!
