### ISSUE TITLE
Indexing C++ issues

### ISSUE THREAD

**Issue by vb000** [cornell-brg/hb-pytorch#54]
I tried using this on [indexing_refactor](https://github.com/cornell-brg/hb-pytorch/tree/indexing_refactor) branch:

https://github.com/cornell-brg/hb-pytorch/blob/d2656d896d0b87105d334f143866792c7df3dcc7/hammerblade/torch/kernel/bsg_tensor.hpp#L87-L88

But seeing this error:
```
               w[co, ci, kh, kw] = 0.0f;
                             ^~
../hammerblade/torch/kernel/kernel_conv.cpp:222:29: warning: left operand of comma operator has no effect [-Wunused-value]
```

I remember this problem before also, my first preference was `[][]..[]` operator, then `[., ., .]`. But I couldn't implement both of these... any suggestions?

**Comment by sampsyo** [comment]
A little Googling suggests that the conventional wisdom for this recommends [currying the subscript operator](https://stackoverflow.com/a/6969904/39182) to allow multiple subscripts like `w[co][ci][kh][kw]`.

Of course, an alternative would be to pass an array of indices, like `w[{co, ci, kh, kw}]`.

**Comment by vb000** [comment]
First option would require recursive calls to the `[]` operator and requires keeping a count of the dimension we are currently in to do that for arbitrary dimensions. After all that, I would have to find a crazy sed command or manually change indexing in different kernels, so implemented the second one :(. Is this acceptable?

**Comment by vb000** [comment]
Also thought about overloading `,` operator to enable `w[co, ci, kh, kw]` (`co`, `ci`, `kh` and `kw` are custom type objects). Not sure if that works, but definitely a potential solution...

**Comment by cbatten** [comment]
The key here is we need to use meta programming. We need to get runtime code for indexing to be super simple. We need the host code to correctly dispatch so that we get a specialized kernel or at least we need to make the common case fast

**Comment by vb000** [comment]
I think the options with indexing we discussed are:

1. Simple indexing code by overloading `()` operator. It's not super nice in terms of readability, but I don't see any technical limitation with this.
2. Indexing by overloading `[]` operator recursively to achieve MDA style (`[][]...[]`) indexing.
3. Indexing by overloading `[]` but requiring user to pass a list instead -- `[{a, b, c}]`.
4. Indexing by overloading `[]` & `,` and defining a custom index datatype to achieve `[a, b, c]` style.

I believe, all these only differ in aesthetics and the underlying data access can be optimized exactly in the same way. Please correct me if I'm wrong...

**Comment by cbatten** [comment]
Maybe it would be fine for us just to provide .at() which can take some number of parameters. So maybe `[i]` is used for linear elementwise indexing (regardless of the number of dimensions) and `.at(i,j,k)` is used for multi-dimensional access ... I think that might be a nice approach ... the only downside is `at()` usually means bounds checking in C++ STL. But I am ok with this since I think `.at()` is a really nice name. Another key point is we need to see if we can use template metaprogramming to avoid trying to deal with different indexing at runtime. We really want to make sure the code is super simple and fast in the common case ...

**Comment by vb000** [comment]
`at(i, j, k)` sounds great! And agree that we should try to implement the `if-else` logic we now have with templates. 

Also, I'll try to move calculations into the constructor if they can be done ahead of time...

**Comment by vb000** [comment]
Just fyi, something that came up in HammerBlade meeting today. Eigen, one of the popular linear algebra C++ libraries supported by PyTorch, also faces exactly the same issues we are facing:

> The operator[] is also overloaded for index-based access in vectors, but keep in mind that C++ doesn't allow operator[] to take more than one argument. We restrict operator[] to vectors, because an awkwardness in the C++ language would make matrix[i,j] compile to the same thing as matrix[j] !

See "Coefficient accessors" section: https://eigen.tuxfamily.org/dox-devel/group__TutorialMatrixClass.html.

**Comment by cbatten** [comment]
Interesting! Maybe we should do the same thing and use `[]` for linear indexing and `(i,j)` for multidimensional indexing without bounds checking and maybe `.at(i,j)` for indexing with bounds checking
